version: '3.9'
services:
  app:
    build: ./app_server
    ports:
      - "80:80"
    networks:
      - ctflvl5
    depends_on:
      - db
    container_name: appctflvl5
  db:
    image: mysql:5.7
    networks:
      - ctflvl5
    environment:
      MYSQL_ROOT_PASSWORD: ctflvl5
      MYSQL_DATABASE: root
      MYSQL_USER: ctflvl5
      MYSQL_PASSWORD: ctflvl5
      MYSQL_ROOT_HOST: '%'
    command: --default-authentication-plugin=mysql_native_password
    container_name: dbctflvl5
  admin:
    build: ./admin
    networks:
      - ctflvl5
    depends_on:
      - app
    container_name: adminctflvl5
  
networks:
  ctflvl5:
    driver: bridge
    name: ctflvl5
      